apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mongodb-secret.yaml
  - mongodb.yaml
  - app-configmap.yaml
  - app-deployment.yaml
  - app-service.yaml

# El script de inicialización es el mismo que usa docker-compose
configMapGenerator:
  - name: mongodb-init
    namespace: bankx
    files:
      - init-mongo.js=mongo-init.js
generatorOptions:
  disableNameSuffixHash: true
